/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

import java.util.Properties

group = "com.ibm.instana.otel"
version = "1.0.0"

// Load local properties from local.properties file if it exists
val localProperties = Properties().apply {
    val file = rootProject.file("local.properties")
    if (file.exists()) {
        file.inputStream().use { load(it) }
    }
}

// A helper function to get environment variables or fallback to local properties
// System environment variables take precedence over local properties, 
fun envOrLocal(name: String): String? =
    System.getenv(name) ?: localProperties.getProperty(name)

// The TAAS Artifactory credentials and URL are required for this project.
val taasDependenciesUrl = envOrLocal("TAAS_ARTIFACTORY_URL")
    ?: error("Missing TAAS_ARTIFACTORY_URL. Set env var or add it to local.properties")
val taasUsername = envOrLocal("TAAS_ARTIFACTORY_USERNAME")
    ?: error("Missing TAAS_ARTIFACTORY_USERNAME. Set env var or add it to local.properties")
val taasPassword = envOrLocal("TAAS_ARTIFACTORY_PASSWORD")
    ?: error("Missing TAAS_ARTIFACTORY_PASSWORD. Set env var or add it to local.properties")


plugins {
    `java-library`
    `maven-publish`
    `jacoco`
}

repositories {
    maven {
        url = uri(taasDependenciesUrl)
        credentials {
            username = taasUsername
            password = taasPassword
        }
    }
}

dependencies {
    api(libs.commons.math3)
    implementation(libs.guava)

    implementation(platform("org.testcontainers:testcontainers-bom:1.21.4"))
    implementation("org.testcontainers:testcontainers")

    testImplementation("org.junit-pioneer:junit-pioneer:1.9.1") // Last version supporting Java 8
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2") // Last 5.x version supporting Java 8
    testImplementation("org.slf4j:slf4j-simple:2.0.9")
    
}

java {
    // Compile with modern JDK but produce Java 8 compatible bytecode
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    jvmArgs(
        "--add-opens=java.base/java.util=ALL-UNNAMED",
        "--add-opens=java.base/java.lang=ALL-UNNAMED"
    )

    testLogging {
        events("passed", "skipped", "failed", "standardOut", "standardError")
        showStandardStreams = true
        showExceptions = true
        showCauses = true
        showStackTraces = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifactId = rootProject.name
        }
    }
    
}